package mcpserver

import (
	"encoding/json"
	"fmt"
	"os"
	"regexp"

	"github.com/YakinAnd/morok/internal/report"
)

var morokDataRe = regexp.MustCompile(`(?s)<script[^>]*id="morok-data"[^>]*>(.*?)</script>`)

// ParseReport reads a morok HTML report from path and returns its embedded
// snapshot. Returns an error if the file can't be read, the morok-data
// script block is missing or its JSON can't be parsed, or the report
// predates the v2 schema (v1 reports don't carry the structured
// severity/CVSS/remediation data the MCP tools need).
func ParseReport(path string) (*report.Snapshot, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading report %s: %w", path, err)
	}

	m := morokDataRe.FindSubmatch(data)
	if m == nil {
		return nil, fmt.Errorf("%s does not look like a morok report (no embedded morok-data block found)", path)
	}

	// First, unmarshal just the version field to check compatibility early
	// (before trying to parse the full schema which may differ in v1)
	var versionCheck struct {
		V int `json:"v"`
	}
	if err := json.Unmarshal(m[1], &versionCheck); err != nil {
		return nil, fmt.Errorf("parsing morok-data in %s: %w", path, err)
	}

	if versionCheck.V < 2 {
		return nil, fmt.Errorf("%s was generated by an older morok version (schema v%d) — regenerate the report with a version that supports vuln-check/MCP data", path, versionCheck.V)
	}

	// Now unmarshal the full v2+ schema
	var snap report.Snapshot
	if err := json.Unmarshal(m[1], &snap); err != nil {
		return nil, fmt.Errorf("parsing morok-data in %s: %w", path, err)
	}

	return &snap, nil
}
